[platformio]
src_dir = src
default_envs = sensor_node_1

[env]
platform = renesas-ra
board = uno_r4_wifi
framework = arduino
monitor_speed = 115200

build_flags =
    -I../common

lib_deps =
    sparkfun/SparkFun u-blox GNSS v3@^3.1.8

[env:sensor_node_1]
build_flags =
    ${env.build_flags}
    -DPURIK_NODE_SLOT=1

[env:sensor_node_2]
build_flags =
    ${env.build_flags}
    -DPURIK_NODE_SLOT=2
