[env:uno_r4_wifi]
platform = renesas-ra
board = uno_r4_wifi
framework = arduino
monitor_speed = 115200

build_flags =
    -I ../common

lib_deps =
    sparkfun/SparkFun u-blox GNSS v3

; Build only the packaged R4 sensor-node application.
src_dir = src
